version: 2
jobs:
  build:
    docker:
      # Use an official CircleCI image.  It doesn't matter which.
      - image: circleci/golang:1.11.5
    steps:
      - checkout
      - run: echo 'export TAG=0.2.0.${CIRCLE_BUILD_NUM}-${CIRCLE_BRANCH}' >> $BASH_ENV
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
            cd .circleci/images/
            docker build -t "dbohdan1/circleci-tcl-gcc-autoconf:$TAG" .
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
            docker push "dbohdan1/circleci-tcl-gcc-autoconf:$TAG"
  test:
    docker:
      - image: dbohdan1/circleci-tcl-gcc-autoconf:latest
    steps:
      - checkout
      - run: ./show-package-versions.tcl
      - run: ./build-sample-extension.tcl

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
